Repository hsu-makeus-challenge/Spring_Boot, pull requests merged in 2025-05, with the labels that each got.

#63 Week7/Mijeong
  mijeong/build.gradle
  mijeong/src/main/java/umc/spring/Application.java
  mijeong/src/main/java/umc/spring/apiPayload/ApiResponse.java
  mijeong/src/main/java/umc/spring/apiPayload/code/BaseCode.java
  mijeong/src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  mijeong/src/main/java/umc/spring/apiPayload/code/DiscordClient.java
  mijeong/src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  mijeong/src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  mijeong/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  mijeong/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  mijeong/src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  mijeong/src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  mijeong/src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  mijeong/src/main/java/umc/spring/config/DiscordFeignConfig.java
  mijeong/src/main/java/umc/spring/converter/TempConverter.java
  mijeong/src/main/java/umc/spring/service/DiscordService/DiscordService.java
  mijeong/src/main/java/umc/spring/service/TempService/TempCommandService.java
  mijeong/src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  mijeong/src/main/java/umc/spring/service/TempService/TempQueryService.java
  mijeong/src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  mijeong/src/main/java/umc/spring/web/controller/TempRestController.java
  mijeong/src/main/java/umc/spring/web/dto/DiscordMessage.java
  mijeong/src/main/java/umc/spring/web/dto/TempRequest.java
  mijeong/src/main/java/umc/spring/web/dto/TempResponse.java
Labels: :sparkles: Feature

#64 Week7/Jinseong
  jinseong/build.gradle
  jinseong/src/main/java/umc/spring/Application.java
  jinseong/src/main/java/umc/spring/apiPayload/ApiResponse.java
  jinseong/src/main/java/umc/spring/apiPayload/code/BaseCode.java
  jinseong/src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  jinseong/src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  jinseong/src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  jinseong/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  jinseong/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  jinseong/src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  jinseong/src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  jinseong/src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  jinseong/src/main/java/umc/spring/converter/TempConverter.java
  jinseong/src/main/java/umc/spring/service/TempService/TempCommandQueryImpl.java
  jinseong/src/main/java/umc/spring/service/TempService/TempQueryService.java
  jinseong/src/main/java/umc/spring/web/controller/TempRestController.java
  jinseong/src/main/java/umc/spring/web/dto/TempDTO/TempRequest.java
  jinseong/src/main/java/umc/spring/web/dto/TempDTO/TempResponse.java
Labels: :sparkles: Feature

#65 Week7/hyeonda
  dahyeon/.gitignore
  dahyeon/build.gradle
  dahyeon/src/main/java/umc/spring/Application.java
  dahyeon/src/main/java/umc/spring/domain/test/controller/ErrorTestController.java
  dahyeon/src/main/java/umc/spring/global/apiPayload/ApiResponse.java
  dahyeon/src/main/java/umc/spring/global/apiPayload/code/BaseCode.java
  dahyeon/src/main/java/umc/spring/global/apiPayload/code/BaseErrorCode.java
  dahyeon/src/main/java/umc/spring/global/apiPayload/code/ErrorReasonDto.java
  dahyeon/src/main/java/umc/spring/global/apiPayload/code/ReasonDto.java
  dahyeon/src/main/java/umc/spring/global/apiPayload/code/status/ErrorStatus.java
  dahyeon/src/main/java/umc/spring/global/apiPayload/code/status/SuccessStatus.java
  dahyeon/src/main/java/umc/spring/global/common/ExceptionDiscordLoggingAspect.java
  dahyeon/src/main/java/umc/spring/global/common/SkipNotification.java
  dahyeon/src/main/java/umc/spring/global/common/domain/TraceFileResource.java
  dahyeon/src/main/java/umc/spring/global/exception/ExceptionAdvice.java
  dahyeon/src/main/java/umc/spring/global/exception/GeneralException.java
  dahyeon/src/main/resources/application-prod.properties
  dahyeon/src/main/resources/application-test.properties
  dahyeon/src/main/resources/application.properties
  dahyeon/src/test/java/umc/spring/global/exception/ExceptionAdviceIntegrationTest.java
  dahyeon/src/test/java/umc/spring/global/exception/ExceptionAdviceTest.java
  dahyeon/src/test/java/umc/spring/global/exception/ExceptionNotificationText.java
  dahyeon/src/test/java/umc/spring/global/mock/InvalidUserInputException.java
  dahyeon/src/test/java/umc/spring/global/mock/NotiException.java
Labels: :sparkles: Feature, :white_check_mark: Test

#67 Week7/junho
  Junho/build.gradle
  Junho/src/main/java/umc/study/Application.java
  Junho/src/main/java/umc/study/apiPayload/ApiResponse.java
  Junho/src/main/java/umc/study/apiPayload/code/BaseCode.java
  Junho/src/main/java/umc/study/apiPayload/code/BaseErrorCode.java
  Junho/src/main/java/umc/study/apiPayload/code/ErrorReasonDTO.java
  Junho/src/main/java/umc/study/apiPayload/code/ReasonDTO.java
  Junho/src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  Junho/src/main/java/umc/study/apiPayload/code/status/SuccessStatus.java
  Junho/src/main/java/umc/study/apiPayload/exception/ExceptionAdvice.java
  Junho/src/main/java/umc/study/apiPayload/exception/GeneralException.java
  Junho/src/main/java/umc/study/apiPayload/exception/handler/TempHandler.java
  Junho/src/main/java/umc/study/converter/TempConverter.java
  Junho/src/main/java/umc/study/repository/UserRepository/UserRepository.java
  Junho/src/main/java/umc/study/service/TempService/TempCommandService.java
  Junho/src/main/java/umc/study/service/TempService/TempCommandServiceImpl.java
  Junho/src/main/java/umc/study/service/TempService/TempQueryService.java
  Junho/src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  Junho/src/main/java/umc/study/web/controller/TempRestController.java
  Junho/src/main/java/umc/study/web/dto/TempRequest.java
  Junho/src/main/java/umc/study/web/dto/TempResponse.java
Labels: :sparkles: Feature

#73 Week7/Hajin
  hajin/build.gradle
  hajin/src/main/java/umc/study/apiPayload/ApiResponse.java
  hajin/src/main/java/umc/study/apiPayload/code/BaseCode.java
  hajin/src/main/java/umc/study/apiPayload/code/BaseErrorCode.java
  hajin/src/main/java/umc/study/apiPayload/code/ErrorReasonDTO.java
  hajin/src/main/java/umc/study/apiPayload/code/ReasonDTO.java
  hajin/src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  hajin/src/main/java/umc/study/apiPayload/code/status/SuccessStatus.java
  hajin/src/main/java/umc/study/apiPayload/exception/ExceptionAdvice.java
  hajin/src/main/java/umc/study/apiPayload/exception/GeneralException.java
  hajin/src/main/java/umc/study/apiPayload/exception/handler/TempHandler.java
  hajin/src/main/java/umc/study/converter/TempConverter.java
  hajin/src/main/java/umc/study/service/TempService/TempCommandService.java
  hajin/src/main/java/umc/study/service/TempService/TempCommandServiceImpl.java
  hajin/src/main/java/umc/study/service/TempService/TempQueryService.java
  hajin/src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  hajin/src/main/java/umc/study/web/controller/TempRestController.java
  hajin/src/main/java/umc/study/web/dto/TempResponse.java
Labels: :sparkles: Feature

#74 Week7/Jonghyeon
  jonghyeon/.gitignore
  jonghyeon/README.md
  jonghyeon/build.gradle
  jonghyeon/src/main/java/umc/spring/StudyApplication.java
  jonghyeon/src/main/java/umc/spring/apiPayload/ApiResponse.java
  jonghyeon/src/main/java/umc/spring/apiPayload/code/BaseCode.java
  jonghyeon/src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  jonghyeon/src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  jonghyeon/src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  jonghyeon/src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  jonghyeon/src/main/java/umc/spring/apiPayload/exception/ErrorStatus.java
  jonghyeon/src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  jonghyeon/src/main/java/umc/spring/apiPayload/exception/handler/ExceptionAdvice.java
  jonghyeon/src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  jonghyeon/src/main/java/umc/spring/converter/TempConverter.java
  jonghyeon/src/main/java/umc/spring/domain/BaseEntity.java
  jonghyeon/src/main/java/umc/spring/domain/Store.java
  jonghyeon/src/main/java/umc/spring/repository/MissionRepository/MissionRepositoryCustom.java
  jonghyeon/src/main/java/umc/spring/service/tempService/TempCommandQueryImpl.java
  jonghyeon/src/main/java/umc/spring/service/tempService/TempQueryService.java
  jonghyeon/src/main/java/umc/spring/service/tempService/TempQueryServiceImpl.java
  jonghyeon/src/main/java/umc/spring/web/controller/TempRestController.java
  jonghyeon/src/main/java/umc/spring/web/dto/TempResponse.java
Labels: :sparkles: Feature

#85 Week8/dahyeon
  dahyeon/build.gradle
  dahyeon/src/main/java/umc/spring/domain/member/controller/MemberController.java
  dahyeon/src/main/java/umc/spring/domain/member/converter/MemberConverter.java
  dahyeon/src/main/java/umc/spring/domain/member/dto/MemberSignUpRequestDto.java
  dahyeon/src/main/java/umc/spring/domain/member/dto/MemberSignUpResponseDto.java
  dahyeon/src/main/java/umc/spring/domain/member/exception/MemberHandler.java
  dahyeon/src/main/java/umc/spring/domain/member/exception/status/MemberErrorStatus.java
  dahyeon/src/main/java/umc/spring/domain/member/service/MemberService.java
  dahyeon/src/main/java/umc/spring/domain/member/service/MemberServiceImpl.java
  dahyeon/src/main/java/umc/spring/domain/mission/controller/MissionController.java
  dahyeon/src/main/java/umc/spring/domain/mission/converter/MissionConverter.java
  dahyeon/src/main/java/umc/spring/domain/mission/dto/MissionCompleteResponseDto.java
  dahyeon/src/main/java/umc/spring/domain/mission/dto/MissionCreateRequestDto.java
  dahyeon/src/main/java/umc/spring/domain/mission/dto/MissionCreateResponseDto.java
  dahyeon/src/main/java/umc/spring/domain/mission/entity/mappings/MemberMission.java
  dahyeon/src/main/java/umc/spring/domain/mission/exception/MissionHandler.java
  dahyeon/src/main/java/umc/spring/domain/mission/exception/status/MissionErrorStatus.java
  dahyeon/src/main/java/umc/spring/domain/mission/repository/MemberMissionRepository.java
  dahyeon/src/main/java/umc/spring/domain/mission/service/MissionService.java
  dahyeon/src/main/java/umc/spring/domain/mission/service/MissionServiceImpl.java
  dahyeon/src/main/java/umc/spring/domain/mission/validation/CheckMission.java
  dahyeon/src/main/java/umc/spring/domain/mission/validation/CheckMissionValidator.java
  dahyeon/src/main/java/umc/spring/domain/store/controller/StoreController.java
  dahyeon/src/main/java/umc/spring/domain/store/converter/StoreConverter.java
  dahyeon/src/main/java/umc/spring/domain/store/dto/ReviewRequestDto.java
  dahyeon/src/main/java/umc/spring/domain/store/dto/ReviewResponseDto.java
  dahyeon/src/main/java/umc/spring/domain/store/entity/Store.java
  dahyeon/src/main/java/umc/spring/domain/store/exception/status/StoreErrorStatus.java
  dahyeon/src/main/java/umc/spring/domain/store/service/ReviewService.java
  dahyeon/src/main/java/umc/spring/domain/store/service/ReviewServiceImpl.java
  dahyeon/src/main/java/umc/spring/domain/store/service/StoreService.java
  dahyeon/src/main/java/umc/spring/domain/store/service/StoreServiceImpl.java
  dahyeon/src/main/java/umc/spring/domain/store/validation/annotation/ExistStore.java
  dahyeon/src/main/java/umc/spring/domain/store/validation/validator/StoresExistValidator.java
  dahyeon/src/main/java/umc/spring/global/config/SwaggerConfig.java
  dahyeon/src/main/java/umc/spring/global/exception/ExceptionAdvice.java
  dahyeon/src/main/resources/application.properties
  dahyeon/src/test/java/umc/spring/domain/store/service/ReviewServiceImplTest.java
  dahyeon/src/test/java/umc/spring/domain/store/service/StoreServiceImplTest.java
Labels: :page_facing_up: Docs, ⚙ Settings, :sparkles: Feature

#93 Week9/Mijeong
  mijeong/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  mijeong/src/main/java/umc/spring/config/WebConfig.java
  mijeong/src/main/java/umc/spring/converter/MissionConverter.java
  mijeong/src/main/java/umc/spring/converter/ReviewConverter.java
  mijeong/src/main/java/umc/spring/converter/StoreMissionConverter.java
  mijeong/src/main/java/umc/spring/converter/UserMissionConverter.java
  mijeong/src/main/java/umc/spring/domain/common/BaseEntity.java
  mijeong/src/main/java/umc/spring/domain/enums/MissionStatus.java
  mijeong/src/main/java/umc/spring/domain/mapping/UserMission.java
  mijeong/src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  mijeong/src/main/java/umc/spring/repository/ReviewRepository/ReviewRepositoryCustom.java
  mijeong/src/main/java/umc/spring/repository/ReviewRepository/ReviewRepositoryImpl.java
  mijeong/src/main/java/umc/spring/repository/StoreMissionRepository/StoreMissionRepository.java
  mijeong/src/main/java/umc/spring/repository/StoreMissionRepository/StoreMissionRepositoryCustom.java
  mijeong/src/main/java/umc/spring/repository/StoreMissionRepository/StoreMissionRepositoryImpl.java
  mijeong/src/main/java/umc/spring/repository/UserMissionRepository/UserMissionRepositoryCustom.java
  mijeong/src/main/java/umc/spring/repository/UserMissionRepository/UserMissionRepositoryImpl.java
  mijeong/src/main/java/umc/spring/service/FoodCategoryService/FoodCategoryQueryServiceImpl.java
  mijeong/src/main/java/umc/spring/service/ReviewService/ReviewQueryService.java
  mijeong/src/main/java/umc/spring/service/ReviewService/ReviewQueryServiceImpl.java
  mijeong/src/main/java/umc/spring/service/StoreMissionService/StoreMissionQueryService.java
  mijeong/src/main/java/umc/spring/service/StoreMissionService/StoreMissionQueryServiceImpl.java
  mijeong/src/main/java/umc/spring/service/UserMissionService/UserMissionCommandService.java
  mijeong/src/main/java/umc/spring/service/UserMissionService/UserMissionCommandServiceImpl.java
  mijeong/src/main/java/umc/spring/service/UserMissionService/UserMissionQueryService.java
  mijeong/src/main/java/umc/spring/service/UserMissionService/UserMissionQueryServiceImpl.java
  mijeong/src/main/java/umc/spring/validation/annotation/CheckPage.java
  mijeong/src/main/java/umc/spring/validation/annotation/ExistUserMission.java
  mijeong/src/main/java/umc/spring/validation/validator/PageCheckValidator.java
  mijeong/src/main/java/umc/spring/validation/validator/UserMissionExistValidator.java
  mijeong/src/main/java/umc/spring/web/controller/ReviewController.java
  mijeong/src/main/java/umc/spring/web/controller/StoreController.java
  mijeong/src/main/java/umc/spring/web/controller/StoreMissionController.java
  mijeong/src/main/java/umc/spring/web/controller/TempRestController.java
  mijeong/src/main/java/umc/spring/web/controller/UserController.java
  mijeong/src/main/java/umc/spring/web/controller/UserMissionController.java
  mijeong/src/main/java/umc/spring/web/dto/mission/MissionResponse.java
  mijeong/src/main/java/umc/spring/web/dto/review/ReviewRequest.java
  mijeong/src/main/java/umc/spring/web/dto/review/ReviewResponse.java
  mijeong/src/main/java/umc/spring/web/dto/store/StoreRequest.java
  mijeong/src/main/java/umc/spring/web/dto/storeMission/StoreMissionResponse.java
  mijeong/src/main/java/umc/spring/web/dto/user/UserRequest.java
  mijeong/src/main/java/umc/spring/web/dto/userMission/UserMissionResponse.java
  mijeong/src/test/java/umc/spring/UserMissionQueryServiceTest.java
Labels: :sparkles: Feature

#94 Week9/Jinseong
  jinseong/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  jinseong/src/main/java/umc/spring/apiPayload/exception/handler/PageHandler.java
  jinseong/src/main/java/umc/spring/apiPayload/exception/handler/UserMissionHandler.java
  jinseong/src/main/java/umc/spring/config/WebConfig.java
  jinseong/src/main/java/umc/spring/converter/StoreConverter.java
  jinseong/src/main/java/umc/spring/converter/UserConverter.java
  jinseong/src/main/java/umc/spring/converter/UserMissionConverter.java
  jinseong/src/main/java/umc/spring/domain/mapping/UserMission.java
  jinseong/src/main/java/umc/spring/repository/ReviewRepository.java
  jinseong/src/main/java/umc/spring/repository/StoreMissionRepository/StoreMissionRepository.java
  jinseong/src/main/java/umc/spring/repository/UserMissionRepository/UserMissionRepository.java
  jinseong/src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  jinseong/src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  jinseong/src/main/java/umc/spring/service/UserMissionService/UserMissionCommandService.java
  jinseong/src/main/java/umc/spring/service/UserMissionService/UserMissionCommandServiceImpl.java
  jinseong/src/main/java/umc/spring/service/UserService/UserQueryService.java
  jinseong/src/main/java/umc/spring/service/UserService/UserQueryServiceImpl.java
  jinseong/src/main/java/umc/spring/validation/annotation/CheckPage.java
  jinseong/src/main/java/umc/spring/validation/resolver/CheckPageArgumentResolver.java
  jinseong/src/main/java/umc/spring/web/controller/MissionRestController.java
  jinseong/src/main/java/umc/spring/web/controller/StoreRestController.java
  jinseong/src/main/java/umc/spring/web/controller/TempRestController.java
  jinseong/src/main/java/umc/spring/web/controller/UserRestController.java
  jinseong/src/main/java/umc/spring/web/dto/MissionDTO/MissionRequestDTO.java
  jinseong/src/main/java/umc/spring/web/dto/MissionDTO/MissionResponseDTO.java
  jinseong/src/main/java/umc/spring/web/dto/StoreDTO/StoreResponseDTO.java
  jinseong/src/main/java/umc/spring/web/dto/UserDTO/UserResponseDTO.java
Labels: :sparkles: Feature

#106 Week9/Jin
  jin/src/main/java/umc/spring/Application.java
  jin/src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  jin/src/main/java/umc/spring/apiPayload/exception/handler/PageNumberHandler.java
  jin/src/main/java/umc/spring/apiPayload/exception/handler/UserIdHandler.java
  jin/src/main/java/umc/spring/config/WebConfig.java
  jin/src/main/java/umc/spring/converter/MissionByUserConverter.java
  jin/src/main/java/umc/spring/converter/MissionConverter.java
  jin/src/main/java/umc/spring/converter/StoreConverter.java
  jin/src/main/java/umc/spring/domain/Mission.java
  jin/src/main/java/umc/spring/domain/Review.java
  jin/src/main/java/umc/spring/domain/Store.java
  jin/src/main/java/umc/spring/domain/User.java
  jin/src/main/java/umc/spring/repository/MissionByUserRepository.java
  jin/src/main/java/umc/spring/repository/MissionRepository.java
  jin/src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  jin/src/main/java/umc/spring/repository/UserRepository.java
  jin/src/main/java/umc/spring/service/MissionService/MissionByUserQueryService.java
  jin/src/main/java/umc/spring/service/MissionService/MissionByUserQueryServiceImpl.java
  jin/src/main/java/umc/spring/service/MissionService/MissionQueryService.java
  jin/src/main/java/umc/spring/service/MissionService/MissionQueryServiceImpl.java
  jin/src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  jin/src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  jin/src/main/java/umc/spring/validation/annotation/ValidPage.java
  jin/src/main/java/umc/spring/validation/validator/ValidPageValidator.java
  jin/src/main/java/umc/spring/web/controller/MissionRestController.java
  jin/src/main/java/umc/spring/web/controller/StoreController.java
  jin/src/main/java/umc/spring/web/controller/StoreRestController.java
  jin/src/main/java/umc/spring/web/controller/UserRestController.java
  jin/src/main/java/umc/spring/web/dto/mission/MissionResponseDTO.java
  jin/src/main/java/umc/spring/web/dto/store/StoreResponseDTO.java
Labels: :sparkles: Feature

#105 Week9/dahyeon
  dahyeon/build.gradle
  dahyeon/src/main/java/umc/spring/domain/member/controller/MemberController.java
  dahyeon/src/main/java/umc/spring/domain/member/service/MemberServiceImpl.java
  dahyeon/src/main/java/umc/spring/domain/mission/converter/MissionConverter.java
  dahyeon/src/main/java/umc/spring/domain/mission/dto/MissionCreateResponseDto.java
  dahyeon/src/main/java/umc/spring/domain/mission/dto/MissionListResponseDto.java
  dahyeon/src/main/java/umc/spring/domain/mission/repository/MissionRepository.java
  dahyeon/src/main/java/umc/spring/domain/mission/service/MissionService.java
  dahyeon/src/main/java/umc/spring/domain/mission/service/MissionServiceImpl.java
  dahyeon/src/main/java/umc/spring/domain/store/controller/StoreController.java
  dahyeon/src/main/java/umc/spring/domain/store/converter/StoreConverter.java
  dahyeon/src/main/java/umc/spring/domain/store/dto/ReviewResponseDto.java
  dahyeon/src/main/java/umc/spring/domain/store/entity/Review.java
  dahyeon/src/main/java/umc/spring/domain/store/repository/ReviewRepository.java
  dahyeon/src/main/java/umc/spring/domain/store/repository/StoreReviewRepository.java
  dahyeon/src/main/java/umc/spring/domain/store/service/ReviewService.java
  dahyeon/src/main/java/umc/spring/domain/store/service/ReviewServiceImpl.java
  dahyeon/src/main/java/umc/spring/global/apiPayload/code/status/ErrorStatus.java
  dahyeon/src/main/java/umc/spring/global/config/WebConfig.java
  dahyeon/src/main/java/umc/spring/global/exception/ExceptionAdvice.java
  dahyeon/src/main/java/umc/spring/global/exception/handler/globalHandler.java
  dahyeon/src/main/java/umc/spring/global/validation/annotation/PageCheck.java
  dahyeon/src/main/java/umc/spring/global/validation/validator/PageArgumentResolver.java
  dahyeon/src/test/java/umc/spring/domain/mission/service/MissionRepositoryPaginationComparisonTest.java
  dahyeon/src/test/java/umc/spring/domain/mission/service/MissionServicePaginationTest.java
  dahyeon/src/test/java/umc/spring/domain/mission/service/testForVsStreamPerformance.java
  dahyeon/src/test/java/umc/spring/domain/store/service/ReviewServiceImplTest.java
  dahyeon/src/test/java/umc/spring/domain/store/service/ReviewServicePaginationTest.java
  dahyeon/src/test/java/umc/spring/global/exception/ExceptionNotificationText.java
  dahyeon/src/test/java/umc/spring/integrationTest/review/PageCheckIntegrationTest.java
  dahyeon/src/test/java/umc/spring/integrationTest/review/StoreReviewIntegrationTest.java
Labels: :sparkles: Feature, :white_check_mark: Test

#104 Week9/Junho
  Junho/build.gradle
  Junho/src/main/java/umc/study/Application.java
  Junho/src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  Junho/src/main/java/umc/study/apiPayload/exception/ExceptionAdvice.java
  Junho/src/main/java/umc/study/apiPayload/exception/InvalidPageException.java
  Junho/src/main/java/umc/study/config/SwaggerConfig.java
  Junho/src/main/java/umc/study/config/WebConfig.java
  Junho/src/main/java/umc/study/converter/MissionConverter.java
  Junho/src/main/java/umc/study/converter/ReviewConverter.java
  Junho/src/main/java/umc/study/converter/StoreConverter.java
  Junho/src/main/java/umc/study/converter/UserMissionConverter.java
  Junho/src/main/java/umc/study/domain/Store.java
  Junho/src/main/java/umc/study/domain/enums/Gender.java
  Junho/src/main/java/umc/study/domain/mapping/UserMission.java
  Junho/src/main/java/umc/study/repository/MissionRepository/MissionRepository.java
  Junho/src/main/java/umc/study/repository/ReviewRepository/ReviewRepository.java
  Junho/src/main/java/umc/study/repository/UserMissionRepository/UserMissionRepository.java
  Junho/src/main/java/umc/study/resolver/CustomPageArgumentResolver.java
  Junho/src/main/java/umc/study/service/MissionService/MissionQueryService.java
  Junho/src/main/java/umc/study/service/MissionService/MissionQueryServiceImpl.java
  Junho/src/main/java/umc/study/service/ReviewService/ReviewService.java
  Junho/src/main/java/umc/study/service/ReviewService/ReviewServiceImpl.java
  Junho/src/main/java/umc/study/service/StoreService/StoreQueryService.java
  Junho/src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
  Junho/src/main/java/umc/study/service/UserMissionService/UserMissionQueryService.java
  Junho/src/main/java/umc/study/service/UserMissionService/UserMissionQueryServiceImpl.java
  Junho/src/main/java/umc/study/validation/annotation/ExistStore.java
  Junho/src/main/java/umc/study/validation/annotation/ValidPageNum.java
  Junho/src/main/java/umc/study/validation/validator/PageNumValidator.java
  Junho/src/main/java/umc/study/validation/validator/StoreExistValidator.java
  Junho/src/main/java/umc/study/web/controller/MissionRestController.java
  Junho/src/main/java/umc/study/web/controller/ReviewRestController.java
  Junho/src/main/java/umc/study/web/controller/StoreRestController.java
  Junho/src/main/java/umc/study/web/controller/UserMissionRestController.java
  Junho/src/main/java/umc/study/web/dto/MissionResponseDTO.java
  Junho/src/main/java/umc/study/web/dto/ReviewRequestDTO.java
  Junho/src/main/java/umc/study/web/dto/ReviewResponseDTO.java
  Junho/src/main/java/umc/study/web/dto/StoreRequestDTO.java
  Junho/src/main/java/umc/study/web/dto/StoreResponseDTO.java
  Junho/src/main/java/umc/study/web/dto/UserMissionResponseDTO.java
Labels: :sparkles: Feature

#95 Week9/Junyong
  junyong/.DS_Store
  junyong/src/main/java/umc/spring/domain/member/converter/MemberMissionConverter.java
  junyong/src/main/java/umc/spring/domain/member/data/PointHistory.java
  junyong/src/main/java/umc/spring/domain/member/data/mapping/MemberMission.java
  junyong/src/main/java/umc/spring/domain/member/repository/memberMission/MemberMissionRepository.java
  junyong/src/main/java/umc/spring/domain/member/repository/pointHistory/PointHistoryRepository.java
  junyong/src/main/java/umc/spring/domain/member/service/MemberCommandService.java
  junyong/src/main/java/umc/spring/domain/member/service/MemberCommandServiceImpl.java
  junyong/src/main/java/umc/spring/domain/member/service/MemberMissionQueryServiceImpl.java
  junyong/src/main/java/umc/spring/domain/member/service/MemberQueryService.java
  junyong/src/main/java/umc/spring/domain/member/service/MemberQueryServiceImpl.java
  junyong/src/main/java/umc/spring/domain/member/web/controller/MemberController.java
  junyong/src/main/java/umc/spring/domain/member/web/dto/MemberResponseDTO.java
  junyong/src/main/java/umc/spring/domain/mission/data/Mission.java
  junyong/src/main/java/umc/spring/domain/mission/data/enums/MissionStatus.java
  junyong/src/main/java/umc/spring/domain/mission/repository/MissionRepository.java
  junyong/src/main/java/umc/spring/domain/mission/validation/annotation/ExistMemberMission.java
  junyong/src/main/java/umc/spring/domain/mission/validation/annotation/MemberMissionExistByMission.java
  junyong/src/main/java/umc/spring/domain/mission/validation/validator/MemberMissionExistByMissionValidator.java
  junyong/src/main/java/umc/spring/domain/mission/validation/validator/MemberMissionExistValidator.java
  junyong/src/main/java/umc/spring/domain/mission/web/controller/MissionController.java
  junyong/src/main/java/umc/spring/domain/review/converter/ReviewConverter.java
  junyong/src/main/java/umc/spring/domain/review/data/Review.java
  junyong/src/main/java/umc/spring/domain/review/repository/ReviewRepository.java
  junyong/src/main/java/umc/spring/domain/review/service/ReviewCommandServiceImpl.java
  junyong/src/main/java/umc/spring/domain/review/service/ReviewQueryService.java
  junyong/src/main/java/umc/spring/domain/review/service/ReviewQueryServiceImpl.java
  junyong/src/main/java/umc/spring/domain/review/web/controller/ReviewController.java
  junyong/src/main/java/umc/spring/domain/review/web/dto/ReviewResponseDTO.java
  junyong/src/main/java/umc/spring/domain/store/converter/StoreConverter.java
  junyong/src/main/java/umc/spring/domain/store/data/Store.java
  junyong/src/main/java/umc/spring/domain/store/repository/StoreRepository.java
  junyong/src/main/java/umc/spring/domain/store/service/StoreQueryService.java
  junyong/src/main/java/umc/spring/domain/store/service/StoreQueryServiceImpl.java
  junyong/src/main/java/umc/spring/domain/store/validation/validator/StoreExistValidator.java
  junyong/src/main/java/umc/spring/domain/store/web/controller/StoreController.java
  junyong/src/main/java/umc/spring/domain/store/web/dto/StoreRequestDTO.java
  junyong/src/main/java/umc/spring/domain/store/web/dto/StoreResponseDTO.java
  junyong/src/main/java/umc/spring/domain/temp/repository/PointHistoryJdbcRepository.java
  junyong/src/main/java/umc/spring/domain/temp/service/TempQueryService.java
  junyong/src/main/java/umc/spring/domain/temp/service/TempQueryServiceImpl.java
  junyong/src/main/java/umc/spring/domain/temp/web/controller/TempRestController.java
  junyong/src/main/java/umc/spring/domain/temp/web/dto/TempResponse.java
  junyong/src/main/java/umc/spring/global/common/apiPayload/code/status/ErrorStatus.java
  junyong/src/main/java/umc/spring/global/common/apiPayload/exception/handler/ErrorHandler.java
  junyong/src/main/java/umc/spring/global/common/config/WebConfig.java
  junyong/src/main/java/umc/spring/global/common/converter/PageConverter.java
  junyong/src/main/java/umc/spring/global/common/dto/PageDTO.java
  junyong/src/main/java/umc/spring/global/common/validation/annotation/PageValid.java
  junyong/src/main/java/umc/spring/global/common/validation/resolver/PageArgumentResolver.java
Labels: :sparkles: Feature
